import { init, showSelect } from './game.js';

window.addEventListener('error',e=>{
  const d=document.getElementById('loading');
  if(d){d.style.display='flex';d.textContent='ERROR: '+e.message;}
});

const I18N={
 en:{points:'POINTS',pointsWithMax:'POINTS (MAX 10)',gameTitle:'MATH CUBE',menu:'MENU',score:'SCORE',tagline:'Think fast. Choose smart.',classic:'CLASSIC',normalMode:'NORMAL MODE',normalDesc:'Explore the 3D Math Cube.',challenge:'CHALLENGE',endlessMode:'ENDLESS MODE',endlessDesc:'Find the equation that is correct.',pointsShop:'POINTS SHOP',language:'LANGUAGE',question:'QUESTION',whichCorrect:'Which equation is correct?',primary:'PRIMARY',highSchool:'HIGH SCHOOL',audience:'AUDIENCE',runOver:'RUN OVER',restart:'RESTART',home:'HOME',hint:'HINT',answerRange:'ANSWER RANGE',askPrimary:'ASK PRIMARY STUDENT',askSecondary:'ASK SECONDARY STUDENT',askAudience:'ASK AUDIENCE',hearts:'POINTS',buy:'BUY',currentPoints:'CURRENT POINTS',newPoints:'NEW POINTS',purchaseComplete:'PURCHASE COMPLETE',notEnoughScore:'NOT ENOUGH SCORE',maxPoints:'MAXIMUM POINTS REACHED',close:'CLOSE',cost:'COST',remainingScore:'REMAINING SCORE',remaining:'REMAINING',seconds:'s',purchaseAdded:'Points added successfully.',starter:'STARTER',primaryLevel:'PRIMARY',primaryAdvanced:'PRIMARY ADVANCED',secondaryLevel:'SECONDARY',secondaryAdvanced:'SECONDARY ADVANCED',areaOf:'Area of',rectangle:'rectangle',volume:'Volume',triangle:'Triangle',solveFor:'Solve for',twoRemoved:'Two incorrect choices have been removed.',mistake:'mistake',mistakes:'mistakes',totalScore:'TOTAL SCORE'},
 'zh-Hant':{points:'點數',pointsWithMax:'點數 (上限 10)',gameTitle:'數學魔方',menu:'選單',score:'分數',tagline:'快速思考，聰明選擇。',classic:'經典',normalMode:'普通模式',normalDesc:'探索 3D 數學魔方。',challenge:'挑戰',endlessMode:'無盡模式',endlessDesc:'找出正確的算式。',pointsShop:'點數商店',language:'語言',question:'題目',whichCorrect:'哪條算式是正確的？',primary:'小學生',highSchool:'中學生',audience:'觀眾',runOver:'本次結束',restart:'重新開始',home:'首頁',hint:'提示',answerRange:'答案範圍',askPrimary:'問小學生',askSecondary:'問中學生',askAudience:'問觀眾',hearts:'點數',buy:'購買',currentPoints:'目前點數',newPoints:'購買後點數',purchaseComplete:'購買成功',notEnoughScore:'分數不足',maxPoints:'點數已達上限',close:'關閉',cost:'價格',remainingScore:'剩餘分數',remaining:'剩餘',seconds:'秒',purchaseAdded:'點數已成功加入。',starter:'入門',primaryLevel:'小學',primaryAdvanced:'小學進階',secondaryLevel:'中學',secondaryAdvanced:'中學進階',areaOf:'面積',rectangle:'長方形',volume:'體積',triangle:'三角形',solveFor:'求',twoRemoved:'已移除兩個錯誤答案。',mistake:'次錯誤',mistakes:'次錯誤',totalScore:'總分'},
 'zh-Hans':{points:'点数',pointsWithMax:'点数 (上限 10)',gameTitle:'數學魔方',menu:'選單',score:'分数',tagline:'快速思考，聪明选择。',classic:'经典',normalMode:'普通模式',normalDesc:'探索 3D 数学魔方。',challenge:'挑战',endlessMode:'无尽模式',endlessDesc:'找出正确的算式。',pointsShop:'点数商店',language:'语言',question:'题目',whichCorrect:'哪条算式是正确的？',primary:'小学生',highSchool:'中学生',audience:'观众',runOver:'本次结束',restart:'重新开始',home:'首页',hint:'提示',answerRange:'答案范围',askPrimary:'问小学生',askSecondary:'问中学生',askAudience:'问观众',hearts:'点数',buy:'购买',currentPoints:'目前点数',newPoints:'购买后点数',purchaseComplete:'购买成功',notEnoughScore:'分数不足',maxPoints:'点数已达上限',close:'关闭',cost:'价格',remainingScore:'剩余分数',remaining:'剩余',seconds:'秒',purchaseAdded:'点数已成功加入。',starter:'入门',primaryLevel:'小学',primaryAdvanced:'小学进阶',secondaryLevel:'中学',secondaryAdvanced:'中学进阶',areaOf:'面积',rectangle:'长方形',volume:'体积',triangle:'三角形',solveFor:'求',twoRemoved:'已移除两个错误答案。',mistake:'次错误',mistakes:'次错误',totalScore:'总分'},
 ja:{points:'ポイント',pointsWithMax:'ポイント (上限 10)',gameTitle:'数学キューブ',menu:'メニュー',score:'スコア',tagline:'すばやく考えて、正しく選ぼう。',classic:'クラシック',normalMode:'ノーマルモード',normalDesc:'3D数学キューブに挑戦。',challenge:'チャレンジ',endlessMode:'エンドレスモード',endlessDesc:'正しい式を選ぼう。',pointsShop:'ポイントショップ',language:'言語',question:'問題',whichCorrect:'正しい式はどれ？',primary:'小学生',highSchool:'中学生',audience:'観客',runOver:'終了',restart:'もう一度',home:'ホーム',hint:'ヒント',answerRange:'答えの範囲',askPrimary:'小学生に聞く',askSecondary:'中学生に聞く',askAudience:'観客に聞く',hearts:'ポイント',buy:'購入',currentPoints:'現在のポイント',newPoints:'購入後のポイント',purchaseComplete:'購入完了',notEnoughScore:'スコア不足',maxPoints:'ポイントは最大です',close:'閉じる',cost:'価格',remainingScore:'残りスコア',remaining:'残り',seconds:'秒',purchaseAdded:'ポイントを追加しました。',starter:'初級',primaryLevel:'小学生',primaryAdvanced:'小学生・発展',secondaryLevel:'中学生',secondaryAdvanced:'中学生・発展',areaOf:'面積',rectangle:'長方形',volume:'体積',triangle:'三角形',solveFor:'求める',twoRemoved:'不正解の選択肢を2つ削除しました。',mistake:'ミス',mistakes:'ミス',totalScore:'合計スコア'},
 ko:{points:'포인트',pointsWithMax:'포인트 (최대 10)',gameTitle:'수학 큐브',menu:'메뉴',score:'점수',tagline:'빠르게 생각하고 똑똑하게 선택하세요.',classic:'클래식',normalMode:'일반 모드',normalDesc:'3D 수학 큐브를 탐험하세요.',challenge:'도전',endlessMode:'무한 모드',endlessDesc:'올바른 식을 찾아보세요.',pointsShop:'포인트 상점',language:'언어',question:'문제',whichCorrect:'올바른 식은 무엇일까요?',primary:'초등학생',highSchool:'중학생',audience:'관객',runOver:'게임 종료',restart:'다시 시작',home:'홈',hint:'힌트',answerRange:'답의 범위',askPrimary:'초등학생에게 묻기',askSecondary:'중학생에게 묻기',askAudience:'관객에게 묻기',hearts:'포인트',buy:'구매',currentPoints:'현재 포인트',newPoints:'구매 후 포인트',purchaseComplete:'구매 완료',notEnoughScore:'점수가 부족합니다',maxPoints:'포인트가 최대입니다',close:'닫기',cost:'가격',remainingScore:'남은 점수',remaining:'남음',seconds:'초',purchaseAdded:'포인트가 추가되었습니다.',starter:'입문',primaryLevel:'초등',primaryAdvanced:'초등 심화',secondaryLevel:'중등',secondaryAdvanced:'중등 심화',areaOf:'넓이',rectangle:'직사각형',volume:'부피',triangle:'삼각형',solveFor:'구하기',twoRemoved:'틀린 선택지 2개를 제거했습니다.',mistake:'회 실수',mistakes:'회 실수',totalScore:'총점'}
};
if(localStorage.mcPointsV2Initialized!=='1'){localStorage.mcHearts='10';localStorage.mcPointsV2Initialized='1';}else if(localStorage.mcHearts===null || Number(localStorage.mcHearts)<0)localStorage.mcHearts='10';if(localStorage.mcScore===null)localStorage.mcScore='0';
let lang=localStorage.mcLang||detectLanguage();
function detectLanguage(){const n=(navigator.language||'en').toLowerCase();if(n.startsWith('zh-hant')||n.includes('hk')||n.includes('tw'))return'zh-Hant';if(n.startsWith('zh'))return'zh-Hans';if(n.startsWith('ja'))return'ja';if(n.startsWith('ko'))return'ko';return'en'}
function t(k){return I18N[lang]?.[k]||I18N.en[k]||k}
function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-mc-i18n]').forEach(e=>e.textContent=t(e.dataset.mcI18n));}
function showHome(){clearInterval(run?.timer);document.querySelectorAll('.mc-screen').forEach(e=>e.classList.remove('mc-active'));document.querySelectorAll('.mc-modal').forEach(e=>e.classList.remove('mc-open'));document.getElementById('mc-home').classList.add('mc-active');document.getElementById('screen-select').classList.remove('active');document.getElementById('screen-result').classList.remove('active');document.getElementById('hud').classList.remove('active');updateWallet();}
function showEndless(){document.querySelectorAll('.mc-screen').forEach(e=>e.classList.remove('mc-active'));document.getElementById('mc-endless-screen').classList.add('mc-active');}
function updateWallet(){const h=localStorage.mcHearts===null ? 10 : Math.min(10,Math.max(0,Number(localStorage.mcHearts)));document.getElementById('mc-score').textContent=localStorage.mcScore||'0';document.getElementById('mc-hearts').textContent='('+h+')';}

window.addEventListener('mathcube-home',showHome);
document.getElementById('mc-normal').addEventListener('click',()=>{document.getElementById('mc-home').classList.remove('mc-active');showSelect();});
document.getElementById('mc-endless-btn').addEventListener('click',()=>{showEndless();startEndless();});
document.getElementById('mc-endless-back').addEventListener('click',showHome);
document.getElementById('mc-language').addEventListener('click',()=>document.getElementById('mc-language-modal').classList.add('mc-open'));
document.getElementById('mc-settings').addEventListener('click',()=>document.getElementById('mc-language-modal').classList.add('mc-open'));
document.getElementById('mc-language-close').addEventListener('click',()=>document.getElementById('mc-language-modal').classList.remove('mc-open'));
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;localStorage.mcLang=lang;applyLanguage();window.dispatchEvent(new Event('mathcube-language-changed'));document.getElementById('mc-language-modal').classList.remove('mc-open');}));
document.getElementById('mc-shop').addEventListener('click',()=>{refreshShop();document.getElementById('mc-shop-modal').classList.add('mc-open')});
document.getElementById('mc-shop-close').addEventListener('click',()=>document.getElementById('mc-shop-modal').classList.remove('mc-open'));
document.getElementById('mc-purchase-close').addEventListener('click',()=>document.getElementById('mc-purchase-modal').classList.remove('mc-open'));document.getElementById('mc-purchase-ok').addEventListener('click',()=>document.getElementById('mc-purchase-modal').classList.remove('mc-open'));
function refreshShop(){const s=Number(localStorage.mcScore||0),h=localStorage.mcHearts===null?10:Math.min(10,Math.max(0,Number(localStorage.mcHearts)));$('mc-shop-score').textContent=s.toLocaleString();$('mc-shop-hearts').textContent=h;const shopMax=$('mc-shop-max'); if(shopMax) shopMax.textContent=10;document.querySelectorAll('.mc-shop-item').forEach(b=>{const amount=Number(b.dataset.points);const canBuy=h+amount<=10 && s>=Number(b.dataset.cost);b.disabled=!canBuy;});}
function showPurchaseResult(title,current,next,detail){$('mc-purchase-title').textContent=title;$('mc-purchase-current').textContent=current;$('mc-purchase-new').textContent=next;$('mc-purchase-detail').textContent=detail;$('mc-purchase-modal').classList.add('mc-open');}
document.querySelectorAll('.mc-shop-item').forEach(b=>b.addEventListener('click',()=>{const s=Number(localStorage.mcScore||0),cost=Number(b.dataset.cost),amount=Number(b.dataset.points),current=localStorage.mcHearts===null?10:Math.min(10,Math.max(0,Number(localStorage.mcHearts)));if(current>=10){showPurchaseResult(t('maxPoints'),current,current,t('maxPoints'));return;}if(s<cost){showPurchaseResult(t('notEnoughScore'),current,current,`${t('cost')}: ${cost.toLocaleString()} · ${t('remainingScore')}: ${s.toLocaleString()}`);return;}const next=Math.min(10,current+amount);localStorage.mcScore=s-cost;localStorage.mcHearts=next;updateWallet();refreshShop();showPurchaseResult(t('purchaseComplete'),current,next,`${t('cost')}: ${cost.toLocaleString()} · ${t('remainingScore')}: ${localStorage.mcScore.toLocaleString()}`);}));

// Endless engine
let run={q:1,score:0,mistakes:0,time:30,timer:null,current:null,hints:{range:3,fifty:2,primary:2,high:2,audience:2}};
const $=id=>document.getElementById(id); const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
function makeQuestion(){
  let q=run.q,a,b,c,ans,display;
  const mode=q<=10?0:q<=25?1:q<=45?2:q<=65?3:4;
  const types=[
    ()=>{a=rnd(3,30);b=rnd(2,25);ans=a+b;display=`${a} + ${b} = ?`},
    ()=>{a=rnd(20,90);b=rnd(2,a);ans=a-b;display=`${a} − ${b} = ?`},
    ()=>{a=rnd(2,12);b=rnd(2,12);ans=a*b;display=`${a} × ${b} = ?`},
    ()=>{b=rnd(2,12);ans=rnd(2,12);a=b*ans;display=`${a} ÷ ${b} = ?`},
    ()=>{a=rnd(40,200);b=rnd(10,90);ans=a+b;display=`${a} + ${b} = ?`},
    ()=>{a=rnd(8,30);b=rnd(2,9);ans=a*b;display=`${a} × ${b} = ?`},
    ()=>{a=rnd(2,9);b=rnd(2,9);c=rnd(2,9);ans=a+b*c;display=`${a} + ${b} × ${c} = ?`},
    ()=>{a=rnd(2,9);b=rnd(2,9);c=rnd(1,9);ans=(a+b)*c;display=`(${a} + ${b}) × ${c} = ?`},
    ()=>{a=rnd(2,12);ans=a*a;display=`${a}² = ?`},
    ()=>{let x=rnd(2,12),k=rnd(2,8);ans=x;display=`${k}x = ${k*x}  →  x = ?`},
    ()=>{let x=rnd(2,12),k=rnd(2,9);ans=x;display=`x + ${k} = ${x+k}  →  x = ?`},
    ()=>{let p=[10,20,25,50][rnd(0,3)],n=rnd(2,10)*10;ans=n*p/100;display=`${p}% × ${n} = ?`},
    ()=>{let x=rnd(3,9);ans=180-2*x;display=lang==='zh-Hant'?`${x}° + ${x}° + ? = 180°`:lang==='zh-Hans'?`${x}° + ${x}° + ? = 180°`:lang==='ja'?`${x}° + ${x}° + ? = 180°`:lang==='ko'?`${x}° + ${x}° + ? = 180°`:`Triangle: ${x}° + ${x}° + ? = 180°`},
    ()=>{a=rnd(2,8);b=rnd(3,8);ans=a*b;display=lang==='en'?`Area of ${a} × ${b} rectangle = ?`:`${t('areaOf')} ${a} × ${b} ${t('rectangle')} = ?`},
    ()=>{a=rnd(2,6);b=rnd(3,8);c=rnd(2,5);ans=a*b*c;display=lang==='en'?`Volume: ${a} × ${b} × ${c} = ?`:`${t('volume')}：${a} × ${b} × ${c} = ?`}
  ];
  const pool=mode===0?types.slice(0,4):mode===1?types.slice(0,6):mode===2?types.slice(0,10):mode===3?types.slice(3):types.slice(6);
  pool[rnd(0,pool.length-1)]();
  const spread=Math.max(2,Math.round(Math.abs(ans)*(.08+Math.min(.12,q/100))));
  const set=new Set([ans]);[-spread,-Math.ceil(spread/2),Math.ceil(spread/2),spread].forEach(x=>set.add(ans+x));
  while(set.size<4)set.add(ans+rnd(-Math.max(3,spread*2),Math.max(3,spread*2)));
  const choices=[...set].slice(0,4).sort(()=>Math.random()-.5);
  return{display,ans,choices,low:ans-Math.max(2,Math.ceil(Math.abs(ans)*.18)),high:ans+Math.max(2,Math.ceil(Math.abs(ans)*.18))}
}
function startEndless(){clearInterval(run.timer);run={q:1,score:0,mistakes:0,time:30,timer:null,current:null,hints:{range:3,fifty:2,primary:2,high:2,audience:2}};updateEndlessHearts();renderQuestion();}
function updateEndlessHearts(){let h=localStorage.mcHearts===null ? 10 : Math.min(10,Math.max(0,Number(localStorage.mcHearts)));$('mc-run-hearts').textContent='('+h+')';$('mc-hearts').textContent='('+h+')';}
function renderQuestion(){run.current=makeQuestion();$('mc-qno').textContent=run.q;$('mc-run-score').textContent=run.score;$('mc-difficulty').textContent=run.q<=10?t('starter'):run.q<=25?t('primaryLevel'):run.q<=45?t('primaryAdvanced'):run.q<=65?t('secondaryLevel'):t('secondaryAdvanced');$('mc-equation').textContent=run.current.display;$('mc-answers').innerHTML=run.current.choices.map((v,i)=>`<button class="mc-answer" data-value="${v}"><span class="mc-answer-label">${'ABCD'[i]}</span><span class="mc-answer-text">${v}</span></button>`).join('');document.querySelectorAll('.mc-answer').forEach(b=>b.addEventListener('click',()=>choose(b)));updateHintCounts();startTimer();}
function startTimer(){clearInterval(run.timer);run.time=Math.max(12,30-Math.min(12,Math.floor(run.q/8)));const start=performance.now();$('mc-time-fill').style.width='100%';run.timer=setInterval(()=>{const left=run.time-(performance.now()-start)/1000;$('mc-time-left').textContent=Math.max(0,left).toFixed(1);$('mc-time-fill').style.width=Math.max(0,left/run.time*100)+'%';if(left<=0){clearInterval(run.timer);wrong(true)}},100)}
function choose(b){clearInterval(run.timer);document.querySelectorAll('.mc-answer').forEach(x=>x.disabled=true);if(Number(b.dataset.value)===run.current.ans){b.classList.add('correct');const gain=100+Math.round(Number($('mc-time-left').textContent)*4)+Math.min(100,run.q*2);run.score+=gain;localStorage.mcScore=Number(localStorage.mcScore||0)+Math.ceil(gain/10);run.q++;setTimeout(renderQuestion,380)}else{b.classList.add('wrong');wrong(false)}}
function wrong(){run.mistakes++;updateEndlessHearts();document.querySelectorAll('.mc-answer').forEach(b=>{if(Number(b.dataset.value)===run.current.ans)b.classList.add('correct')});setTimeout(()=>{if(run.mistakes>=3)endRun();else{run.q++;renderQuestion()}},750)}
function endRun(){clearInterval(run.timer);$('mc-result-title').textContent=`${t('question')} ${run.q}`;$('mc-result-score').textContent=run.score;const mistakeLabel=run.mistakes===1?t('mistake'):t('mistakes');$('mc-result-detail').textContent=`${run.mistakes} ${mistakeLabel} · ${t('totalScore')} ${Number(localStorage.mcScore||0)}`;$('mc-result').classList.add('mc-open')}
function updateHintCounts(){Object.entries(run.hints).forEach(([k,v])=>{const id={range:'mc-range',fifty:'mc-fifty',primary:'mc-primary',high:'mc-high',audience:'mc-audience'}[k];$(id).textContent=`${t('remaining')} (${v})`;$(id).parentElement.disabled=v<=0})}
function openHint(type){if(!run.hints[type])return;run.hints[type]--;updateHintCounts();$('mc-hint-modal').classList.add('mc-open');$('mc-audience-bars').innerHTML='';$('mc-hint-title').textContent={range:t('answerRange'),fifty:'50/50',primary:t('askPrimary'),high:t('askSecondary'),audience:t('askAudience')}[type];$('mc-hint-visual').textContent='';if(type==='range')$('mc-hint-text').textContent=`${run.current.low} – ${run.current.high}`;if(type==='fifty'){[...document.querySelectorAll('.mc-answer')].filter(b=>Number(b.dataset.value)!==run.current.ans).sort(()=>Math.random()-.5).slice(0,2).forEach(b=>b.classList.add('removed'));$('mc-hint-text').textContent=t('twoRemoved')}if(type==='primary'||type==='high'){const reliability=type==='primary'?Math.max(.35,.94-run.q*.008):Math.max(.55,.97-run.q*.004);const correct=Math.random()<reliability;const answer=correct?run.current.ans:run.current.choices.filter(x=>x!==run.current.ans)[rnd(0,2)];$('mc-hint-text').textContent=`"${answer}"`;$('mc-hint-visual').textContent=type==='primary'?t('askPrimary'):t('askSecondary')}if(type==='audience'){let weights=run.current.choices.map(()=>Math.random()*30+5);weights[run.current.choices.indexOf(run.current.ans)]+=Math.random()*25;const total=weights.reduce((a,b)=>a+b,0);run.current.choices.forEach((v,i)=>{const p=Math.round(weights[i]/total*100);$('mc-audience-bars').insertAdjacentHTML('beforeend',`<div class="mc-audience-row"><span>${'ABCD'[i]}</span><div class="mc-bar" style="width:${Math.max(8,p)}%">${p}%</div></div>`)})}}

document.querySelectorAll('.mc-hint').forEach(b=>b.addEventListener('click',()=>openHint(b.dataset.hint)));$('mc-hint-close').addEventListener('click',()=>$('mc-hint-modal').classList.remove('mc-open'));$('mc-restart').addEventListener('click',()=>{$('mc-result').classList.remove('mc-open');startEndless()});$('mc-result-home').addEventListener('click',()=>{$('mc-result').classList.remove('mc-open');showHome()});

applyLanguage();
init();
