import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { dom } from './dom.js';
export { THREE };
export const scene=new THREE.Scene();
scene.background=new THREE.Color(0x07121b);
export const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,0.1,100);
camera.position.set(7,5,7);
export const renderer=new THREE.WebGLRenderer({antialias:true});
renderer.setSize(innerWidth,innerHeight);
renderer.setPixelRatio(Math.min(devicePixelRatio,2));
renderer.shadowMap.enabled=true;
renderer.shadowMap.type=THREE.PCFSoftShadowMap;
dom.canvas.appendChild(renderer.domElement);
export const controls=new OrbitControls(camera,renderer.domElement);
controls.enableDamping=true;controls.enablePan=false;controls.enableRotate=true;controls.minDistance=5;controls.maxDistance=15;controls.minPolarAngle=Math.PI/2;controls.maxPolarAngle=Math.PI/2;
controls.autoRotate=false;
scene.add(new THREE.AmbientLight(0xffffff,1.1));
const dir=new THREE.DirectionalLight(0xffffff,1.8);dir.position.set(5,8,6);
dir.castShadow=true;dir.shadow.mapSize.set(1024,1024);
dir.shadow.camera.left=-7;dir.shadow.camera.right=7;
dir.shadow.camera.top=7;dir.shadow.camera.bottom=-7;
scene.add(dir);
const pl1=new THREE.PointLight(0x00f5d4,12,0,2);pl1.position.set(-4,4,4);scene.add(pl1);
const pl2=new THREE.PointLight(0x8b5cf6,12,0,2);pl2.position.set(4,-4,-4);scene.add(pl2);
export const raycaster=new THREE.Raycaster();
export const mouse=new THREE.Vector2();
